✨ Add `caphv-use=allow` tag for device usage
hivelocity/cluster-api-provider-hivelocity pull request #116
Opened 2023-11-02 06:19 UTC by aniruddha2000

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #115 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

2023-11-02 07:21 UTC, janiskemper requested changes

2023-11-02 07:21 UTC, janiskemper commented on pkg/services/hivelocity/hvtag/hvtag.go
> +	DeviceTagKeyClusterUse DeviceTagKey = "caphv-use"
name it DeviceTagKeyCAPHVUseAllowed

2023-11-02 07:21 UTC, janiskemper commented on pkg/services/hivelocity/hvtag/hvtag.go
> +		// get DeviceTag from tagStringdeviceTagFromString
??

2023-11-02 07:21 UTC, janiskemper commented on pkg/services/hivelocity/hvtag/hvtag.go
> +func DeviceUsableByCAPI(tagList []string) (bool, error) {
this function should return a boolean and no error. The question is just yes or no. If something is wrong, then it's a no.

2023-11-02 07:38 UTC, janiskemper approved these changes

2023-11-02 17:04 UTC, janiskemper approved these changes

2023-11-17 12:20 UTC, janiskemper commented
@guettli plz have a look at the docs and approve if they match your expectations

2023-11-17 14:30 UTC, guettli commented on docs/book/src/developer/setup.md
>  See [Provisioning Machines](../topics/provisioning-machines.md) for more about this.
@aniruddha2000 please add this to the file provisioning-machines.md, too.

2023-11-20 07:56 UTC, guettli approved these changes
lgtm.

2023-11-20 08:33 UTC, aniruddha2000 commented
@guettli the e2e fails, is there anything else need changes

2023-11-20 09:54 UTC, janiskemper commented
I looked into the e2e test dump to understand myself what might be going on, but it looks like the server was provisioned. @guettli is this server maybe stuck now in some way?

```
{"level":"DEBUG","time":"2023-11-20T08:14:48.610Z","file":"device/device.go:645","message":"Completed function","controller":"hivelocitymachine","controllerGroup":"infrastructure.cluster.x-k8s.io","controllerKind":"HivelocityMachine","HivelocityMachine":{"name":"caphv-3r9grv-md-0-5nhvp","namespace":"caphv-54cb2q"},"namespace":"caphv-54cb2q","name":"caphv-3r9grv-md-0-5nhvp","reconcileID":"b4104766-4a0d-4e10-9073-5c2a5405fa75","HivelocityMachine":{"name":"caphv-3r9grv-md-0-5nhvp","namespace":"caphv-54cb2q"},"Machine":{"name":"caphv-3r9grv-md-0-595ccf6bf7x6656b-67rnr","namespace":"caphv-54cb2q"},"Cluster":{"name":"caphv-3r9grv","namespace":"caphv-54cb2q"},"HivelocityCluster":{"name":"caphv-3r9grv","namespace":"caphv-54cb2q"},"function":"actionDeviceProvisioned","DeviceId":14730,"PowerStatus":"ON","script":"#cloud-config\n## template: jinja\n#cloud-config\n\nwr"}
{"level":"DEBUG","time":"2023-11-20T08:14:48.611Z","file":"device/state_machine.go:84","message":"ReconcileState","controller":"hivelocitymachine","controllerGroup":"infrastructure.cluster.x-k8s.io","controllerKind":"HivelocityMachine","HivelocityMachine":{"name":"caphv-3r9grv-md-0-5nhvp","namespace":"caphv-54cb2q"},"namespace":"caphv-54cb2q","name":"caphv-3r9grv-md-0-5nhvp","reconcileID":"b5164c3a-8149-41f4-89b8-c8f40b208dff","HivelocityMachine":{"name":"caphv-3r9grv-md-0-5nhvp","namespace":"caphv-54cb2q"},"Machine":{"name":"caphv-3r9grv-md-0-595ccf6bf7x6656b-67rnr","namespace":"caphv-54cb2q"},"Cluster":{"name":"caphv-3r9grv","namespace":"caphv-54cb2q"},"HivelocityCluster":{"name":"caphv-3r9grv","namespace":"caphv-54cb2q"},"caller":"state-machine","initialState.ProvisioningState":"provisioned"}
```

2023-11-20 15:21 UTC, guettli commented
I look into the logs.

If I remove debug-level logs, then these changes are the last before the cluster got deleted:


```
level: INFO
time: "2023-11-20T07:57:08.555Z"
file: client/hvclient.go:167
message: calling ProvisionDevice()
controller: hivelocitymachine
controllerGroup: infrastructure.cluster.x-k8s.io
controllerKind: HivelocityMachine
HivelocityMachine:
  name: caphv-3r9grv-md-0-5nhvp
  namespace: caphv-54cb2q
namespace: caphv-54cb2q
name: caphv-3r9grv-md-0-5nhvp
reconcileID: 662fd9c2-e3f5-4af3-9796-6fd29b5999b7
HivelocityMachine:
  name: caphv-3r9grv-md-0-5nhvp
  namespace: caphv-54cb2q
Machine:
  name: caphv-3r9grv-md-0-595ccf6bf7x6656b-67rnr
  namespace: caphv-54cb2q
Cluster:
  name: caphv-3r9grv
  namespace: caphv-54cb2q
HivelocityCluster:
  name: caphv-3r9grv
  namespace: caphv-54cb2q
DeviceID: 14730
hostname: caphv-3r9grv-md-0-5nhvp.example.com
OsName: Ubuntu 20.x
script: |-
  #cloud-config
  ## template: jinja
  #cloud-config

  wr
ForceReload: true
---
level: INFO
time: "2023-11-20T07:57:21.866Z"
file: client/hvclient.go:178
message: ProvisionDevice() was successful (PutBareMetalDeviceIdResource)
controller: hivelocitymachine
controllerGroup: infrastructure.cluster.x-k8s.io
controllerKind: HivelocityMachine
HivelocityMachine:
  name: caphv-3r9grv-md-0-5nhvp
  namespace: caphv-54cb2q
namespace: caphv-54cb2q
name: caphv-3r9grv-md-0-5nhvp
reconcileID: 662fd9c2-e3f5-4af3-9796-6fd29b5999b7
HivelocityMachine:
  name: caphv-3r9grv-md-0-5nhvp
  namespace: caphv-54cb2q
Machine:
  name: caphv-3r9grv-md-0-595ccf6bf7x6656b-67rnr
  namespace: caphv-54cb2q
Cluster:
  name: caphv-3r9grv
  namespace: caphv-54cb2q
HivelocityCluster:
  name: caphv-3r9grv
  namespace: caphv-54cb2q
DeviceID: 14730
---
level: INFO
time: "2023-11-20T07:57:21.866Z"
file: device/state_machine.go:68
message: changing provisioning state
controller: hivelocitymachine
controllerGroup: infrastructure.cluster.x-k8s.io
controllerKind: HivelocityMachine
HivelocityMachine:
  name: caphv-3r9grv-md-0-5nhvp
  namespace: caphv-54cb2q
namespace: caphv-54cb2q
name: caphv-3r9grv-md-0-5nhvp
reconcileID: 662fd9c2-e3f5-4af3-9796-6fd29b5999b7
HivelocityMachine:
  name: caphv-3r9grv-md-0-5nhvp
  namespace: caphv-54cb2q
Machine:
  name: caphv-3r9grv-md-0-595ccf6bf7x6656b-67rnr
  namespace: caphv-54cb2q
Cluster:
  name: caphv-3r9grv
  namespace: caphv-54cb2q
HivelocityCluster:
  name: caphv-3r9grv
  namespace: caphv-54cb2q
caller: state-machine
old: provision-device
new: provisioned
---
level: INFO
time: "2023-11-20T08:16:44.278Z"
file: controllers/hivelocitycluster_controller.go:101
message: Starting reconciling cluster
controller: hivelocitycluster
controllerGroup: infrastructure.cluster.x-k8s.io
controllerKind: HivelocityCluster
HivelocityCluster:
  name: caphv-3r9grv
  namespace: caphv-54cb2q
namespace: caphv-54cb2q
name: caphv-3r9grv
reconcileID: 62d47db5-642e-48b2-bb83-00ce74dcdfaf
HivelocityCluster:
  name: caphv-3r9grv
  namespace: caphv-54cb2q
```

2023-11-20 16:01 UTC, guettli commented
@aniruddha2000 @janiskemper I guess it takes sometimes a bit longer. I created a new PR to increase the time the CI waits: https://github.com/hivelocity/cluster-api-provider-hivelocity/pull/122

2023-11-20 20:11 UTC, guettli commented
@aniruddha2000 this PR was merged. Please rebase on the current main branch and try it again: https://github.com/hivelocity/cluster-api-provider-hivelocity/pull/122

2023-11-23 15:42 UTC, aniruddha2000 commented
@guettli I rebased but seems again failed

2023-12-11 07:44 UTC, merged