🌱 update to go 1.21
hivelocity/cluster-api-provider-hivelocity pull request #125
Opened 2023-11-21 21:44 UTC by kranurag7

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

2023-12-13 11:35 UTC, batistein submitted a review, later dismissed

2023-12-13 11:51 UTC, janiskemper requested changes

2023-12-13 11:51 UTC, janiskemper commented on controllers/hivelocitymachine_controller.go
> +		log := log.FromContext(ctx)
two options: either name it "logger" or use another function than log.FromContext. I believe you could use the ctrl packagr well. this way you do an import shadow

2023-12-13 11:51 UTC, janiskemper commented on main.go
> +	syncPeriod                   time.Duration
do you have a flag for this?

2023-12-13 12:45 UTC, janiskemper submitted a review, later dismissed

2023-12-22 10:09 UTC, guettli requested changes
First we need to check that via Tilt. Then we can solve the e2e tests.

2024-02-02 14:21 UTC, guettli submitted a review, later dismissed

2024-02-07 10:41 UTC, guettli commented
we splitted this big PR into two:

https://github.com/hivelocity/cluster-api-provider-hivelocity/pull/139

https://github.com/hivelocity/cluster-api-provider-hivelocity/pull/140

2024-02-08 13:28 UTC, closed without merging